baseURL                = "https://kerman114.github.io/hugo1/"
locale                 = "en-us"
title                  = "Kerman's Blog"
theme                  = "hugo-theme-stack-4.0.3"
defaultContentLanguage = "zh"
hasCJKLanguage         = true
copyright = "Kerman"

[pagination]
    pagerSize = 3

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
